name: porespy_examples
channels:
- conda-forge
- defaults
dependencies:
- python=3.6
- atlas
- numpy
- scipy
- matplotlib
- pandas
- dill
- pyyaml
- jupyter
- scikit-image
- numba
- pytest
- codecov
- coverage
- pep8
- pytest-cache
- pytest-cov
- pytest-pep8
- pip:
  - imageio
  - porespy
  - git+https://github.com/PMEAL/OpenPNM/@updating_percolation
  - tqdm
  - gitpython